/**
 * Seeds N products into one organization, for exercising the Free plan's
 * 20-product limit without clicking through the UI 20 times.
 *
 * Run with: npx tsx src/scripts/seedProducts.ts <org-slug> [count]
 * e.g.:     npx tsx src/scripts/seedProducts.ts acme-inc 20
 */
import dns from 'dns';
import mongoose from 'mongoose';
import { env } from '../config/env';
import { Organization } from '../modules/organizations/organization.model';
import { Product } from '../modules/product/product.model';

dns.setServers(['8.8.8.8', '1.1.1.1']);

async function seed() {
  const slug = process.argv[2];
  const count = parseInt(process.argv[3] ?? '20', 10);

  if (!slug) {
    console.error('Usage: npx tsx src/scripts/seedProducts.ts <org-slug> [count]');
    process.exit(1);
  }

  await mongoose.connect(env.mongoUri);
  console.log('Connected to MongoDB — seeding products...');

  const org = await Organization.findOne({ slug });
  if (!org) {
    console.error(`No organization found with slug "${slug}"`);
    await mongoose.disconnect();
    process.exit(1);
  }

  for (let i = 1; i <= count; i++) {
    const sku = `SEED-${String(i).padStart(4, '0')}`;
    const result = await Product.findOneAndUpdate(
      { organizationId: org._id, sku },
      {
        $set: {
          organizationId: org._id,
          name: `Seed Product ${i}`,
          sku,
          description: 'Generated by seedProducts.ts for plan-limit testing',
          price: 1000 + i * 100, // paise
          stock: 10 + i,
          isActive: true,
        },
      },
      { upsert: true, returnDocument: 'after', setDefaultsOnInsert: true }
    );
    console.log(`  ✓ ${result.name} — ${result._id}`);
  }

  console.log(`Done. Seeded ${count} products for "${org.name}".`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});